version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rekognition-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-q176tpommph7"
s3_prefix = "rekognition-test"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketNamePrefix=\"rekognition-test\" CollectionIdParameter=\"\""
