version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rekognition-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d55gq8zb6b9f"
s3_prefix = "rekognition-test"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketNamePrefix=\"rekognition-test\" CollectionIdParameter=\"\""
