version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "community-bucket"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d55gq8zb6b9f"
s3_prefix = "community-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"community.octank.edu.rwang5688.com\" RetentionPeriodDays=\"730\" DistributionId=\"E26TLCVMBX0MYL\" CollectionIdParameter=\"\" OffensiveLabels=\"Explicit Nudity, Gambling, Suggestive, Violence\" ConfidenceThreshold=\"67\" RootUrl=\"https://community.octank.edu.rwang5688.com/\" TopicName=\"community-octank-edu-detect-moderation-labels\" TopicArn=\"arn:aws:sns:us-east-1:375205257662:community-octank-edu-detect-moderation-labels\""
